# Firebase App Hosting Configuration
# This project uses Firebase Hosting (static) instead of App Hosting (serverless)
# Disable automatic builds by setting build to false

# To use Firebase App Hosting instead, change next.config.js output to 'standalone'
# and enable the build configuration below

runConfig:
  concurrency: 100
  cpu: 1
  maxInstances: 100
  minInstances: 0
  memoryMiB: 512

# Uncomment to enable App Hosting builds:
# env:
#   - variable: NODE_ENV
#     value: production
