import os

types_dir = "lib/types"
index_path = os.path.join(types_dir, "index.ts")

print(f"Scanning {types_dir} for type definitions...")

files = [f for f in os.listdir(types_dir) if f.endswith(".ts") or f.endswith(".tsx")]
files.sort()

exports = []
for f in files:
    if f == "index.ts":
        continue
    
    # Remove extension
    module_name = os.path.splitext(f)[0]
    exports.append(f'export * from "./{module_name}"')

index_content = """/**
 * Barrel export for all type modules
 * Simplifies imports: import { PersonProfile, MasterProject } from "@/lib/types"
 * Auto-generated by generate_index_ts.py
 */

""" + "\n".join(exports) + "\n"

try:
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(index_content)
    print(f"Successfully generated {index_path} with {len(exports)} exports.")
    print("Exports included:")
    for e in exports:
        print(f"  - {e}")
except Exception as e:
    print(f"Error writing index.ts: {e}")
