"use client"

import React, { useState } from "react"
import { ChevronDown, ChevronUp, DollarSign, Clock, AlertTriangle } from "lucide-react"
import type { ProtocolStructure } from "@/lib/ai/types"
import {
  ConfidenceScoreCard,
  ProtocolStepWithConfidence,
  MaterialWithConfidence,
  ConfidenceHighlighter,
} from "./ConfidenceHighlighter"
import { Button } from "@/components/ui/button"

interface AIProtocolViewerProps {
  protocol: ProtocolStructure
  cost?: number
  latency?: number
  provider?: string
  onAccept?: () => void
  onReject?: () => void
  onEditStep?: (stepNumber: number, newInstruction: string) => void
}

/**
 * AI Protocol Viewer Component
 * Displays structured protocol with confidence highlighting
 * Shows cost, latency, and quality metrics
 */
export function AIProtocolViewer({
  protocol,
  cost,
  latency,
  provider = "OpenAI",
  onAccept,
  onReject,
  onEditStep,
}: AIProtocolViewerProps) {
  const [expandedSections, setExpandedSections] = useState({
    objective: true,
    materials: true,
    equipment: true,
    steps: true,
    qc: false,
    troubleshooting: false,
  })

  const toggleSection = (section: keyof typeof expandedSections) => {
    setExpandedSections((prev) => ({
      ...prev,
      [section]: !prev[section],
    }))
  }

  // Format latency
  const formatLatency = (ms: number) => {
    if (ms < 1000) return `${ms}ms`
    return `${(ms / 1000).toFixed(1)}s`
  }

  // Check if protocol needs review
  const needsReview = protocol.confidence < 85 ||
    protocol.steps.some((step) => (step.confidence || protocol.confidence) < 70)

  return (
    <div className="bg-white rounded-lg shadow-lg p-6 space-y-6 max-w-4xl">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">Structured Protocol</h2>
          <p className="text-sm text-gray-500 mt-1">
            Generated by {provider} AI
          </p>
        </div>

        {/* Metrics */}
        <div className="flex gap-4 text-sm text-gray-600">
          {cost !== undefined && (
            <div className="flex items-center gap-1">
              <DollarSign className="h-4 w-4" />
              <span>${cost.toFixed(3)}</span>
            </div>
          )}
          {latency !== undefined && (
            <div className="flex items-center gap-1">
              <Clock className="h-4 w-4" />
              <span>{formatLatency(latency)}</span>
            </div>
          )}
        </div>
      </div>

      {/* Confidence Score */}
      <ConfidenceScoreCard score={protocol.confidence} showDetails />

      {/* Warning if needs review */}
      {needsReview && (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 flex gap-3">
          <AlertTriangle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-amber-800">
            <p className="font-semibold mb-1">Review Required</p>
            <p>
              This protocol contains sections with low confidence. Please review all
              highlighted areas and edit as needed before saving.
            </p>
          </div>
        </div>
      )}

      {/* Objective */}
      {protocol.objective && (
        <div className="space-y-2">
          <button
            onClick={() => toggleSection("objective")}
            className="flex items-center justify-between w-full text-left"
          >
            <h3 className="text-lg font-semibold text-gray-900">Objective</h3>
            {expandedSections.objective ? (
              <ChevronUp className="h-5 w-5 text-gray-400" />
            ) : (
              <ChevronDown className="h-5 w-5 text-gray-400" />
            )}
          </button>
          {expandedSections.objective && (
            <div className="pl-4">
              <p className="text-gray-700">{protocol.objective}</p>
            </div>
          )}
        </div>
      )}

      {/* Materials */}
      {protocol.materials && protocol.materials.length > 0 && (
        <div className="space-y-3">
          <button
            onClick={() => toggleSection("materials")}
            className="flex items-center justify-between w-full text-left"
          >
            <h3 className="text-lg font-semibold text-gray-900">
              Materials ({protocol.materials.length})
            </h3>
            {expandedSections.materials ? (
              <ChevronUp className="h-5 w-5 text-gray-400" />
            ) : (
              <ChevronDown className="h-5 w-5 text-gray-400" />
            )}
          </button>
          {expandedSections.materials && (
            <div className="pl-4 space-y-3">
              {protocol.materials.map((material, idx) => (
                <MaterialWithConfidence
                  key={idx}
                  material={material}
                  overallConfidence={protocol.confidence}
                />
              ))}
            </div>
          )}
        </div>
      )}

      {/* Equipment */}
      {protocol.equipment && protocol.equipment.length > 0 && (
        <div className="space-y-3">
          <button
            onClick={() => toggleSection("equipment")}
            className="flex items-center justify-between w-full text-left"
          >
            <h3 className="text-lg font-semibold text-gray-900">
              Equipment ({protocol.equipment.length})
            </h3>
            {expandedSections.equipment ? (
              <ChevronUp className="h-5 w-5 text-gray-400" />
            ) : (
              <ChevronDown className="h-5 w-5 text-gray-400" />
            )}
          </button>
          {expandedSections.equipment && (
            <div className="pl-4 space-y-2">
              {protocol.equipment.map((item, idx) => (
                <div key={idx} className="text-gray-700">
                  <span className="font-medium">{item.name}</span>
                  {item.model && <span className="text-gray-500"> ({item.model})</span>}
                  {item.settings && (
                    <div className="text-sm text-gray-600 ml-4">
                      Settings: {typeof item.settings === 'string'
                        ? item.settings
                        : JSON.stringify(item.settings)}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Steps */}
      {protocol.steps && protocol.steps.length > 0 && (
        <div className="space-y-3">
          <button
            onClick={() => toggleSection("steps")}
            className="flex items-center justify-between w-full text-left"
          >
            <h3 className="text-lg font-semibold text-gray-900">
              Procedure ({protocol.steps.length} steps)
            </h3>
            {expandedSections.steps ? (
              <ChevronUp className="h-5 w-5 text-gray-400" />
            ) : (
              <ChevronDown className="h-5 w-5 text-gray-400" />
            )}
          </button>
          {expandedSections.steps && (
            <div className="pl-4 space-y-6">
              {protocol.steps.map((step) => (
                <ProtocolStepWithConfidence
                  key={step.stepNumber}
                  step={step}
                  overallConfidence={protocol.confidence}
                  onEditInstruction={onEditStep}
                />
              ))}
            </div>
          )}
        </div>
      )}

      {/* Quality Control */}
      {protocol.qc && (
        <div className="space-y-2">
          <button
            onClick={() => toggleSection("qc")}
            className="flex items-center justify-between w-full text-left"
          >
            <h3 className="text-lg font-semibold text-gray-900">Quality Control</h3>
            {expandedSections.qc ? (
              <ChevronUp className="h-5 w-5 text-gray-400" />
            ) : (
              <ChevronDown className="h-5 w-5 text-gray-400" />
            )}
          </button>
          {expandedSections.qc && (
            <div className="pl-4">
              <p className="text-gray-700">{protocol.qc}</p>
            </div>
          )}
        </div>
      )}

      {/* Troubleshooting */}
      {protocol.troubleshooting && (
        <div className="space-y-2">
          <button
            onClick={() => toggleSection("troubleshooting")}
            className="flex items-center justify-between w-full text-left"
          >
            <h3 className="text-lg font-semibold text-gray-900">Troubleshooting</h3>
            {expandedSections.troubleshooting ? (
              <ChevronUp className="h-5 w-5 text-gray-400" />
            ) : (
              <ChevronDown className="h-5 w-5 text-gray-400" />
            )}
          </button>
          {expandedSections.troubleshooting && (
            <div className="pl-4">
              <p className="text-gray-700">{protocol.troubleshooting}</p>
            </div>
          )}
        </div>
      )}

      {/* Actions */}
      {(onAccept || onReject) && (
        <div className="flex gap-3 pt-4 border-t border-gray-200">
          {onReject && (
            <Button onClick={onReject} variant="outline" className="flex-1">
              Cancel
            </Button>
          )}
          {onAccept && (
            <Button
              onClick={onAccept}
              className="flex-1 bg-brand-500 hover:bg-brand-600 text-white"
              disabled={needsReview}
            >
              {needsReview ? "Review Required" : "Save to Lab Notebook"}
            </Button>
          )}
        </div>
      )}

      {/* Instructions */}
      <div className="text-xs text-gray-500 bg-gray-50 rounded p-3">
        <p className="font-medium mb-1">How to use this protocol:</p>
        <ul className="list-disc list-inside space-y-1 ml-2">
          <li>Green highlights = High confidence (85%+)</li>
          <li>Yellow highlights = Medium confidence (70-84%)</li>
          <li>Red highlights = Low confidence (&lt;70%) - Review required</li>
          <li>Click &ldquo;Edit&rdquo; on any section to make corrections</li>
          <li>All edits are saved when you accept the protocol</li>
        </ul>
      </div>
    </div>
  )
}
