/**
 * Privacy Verification Script
 * 
 * Verifies that Firestore security rules are correctly enforcing user privacy.
 * Uses the Client SDK with custom tokens generated by Admin SDK to simulate real users.
 * 
 * SCENARIOS:
 * 1. Notification Privacy: User A cannot read User B's notifications.
 * 2. User Profile Privacy: User A can read User B's profile (for collaboration).
 * 3. Project Privacy: User A cannot read User B's private project (unless shared).
 * 
 * USAGE:
 *   npx tsx scripts/verify_privacy.ts
 */

import * as admin from 'firebase-admin'
import { initializeApp } from 'firebase/app'
import { getAuth, signInWithCustomToken } from 'firebase/auth'
import { getFirestore, doc, getDoc } from 'firebase/firestore'
import * as fs from 'fs'

// --- Configuration ---
const FIREBASE_CONFIG = {
    projectId: 'momentum-a60c5',
    apiKey: 'AIzaSyBYCLKByD0NlVehUynesxeciHPrOGD4NUU'
}

// Try to read service account
const serviceAccountPath = process.env.FIREBASE_SERVICE_ACCOUNT_KEY || './service-account-key.json'
if (!fs.existsSync(serviceAccountPath)) {
    console.error('❌ Service account not found. Cannot mint custom tokens.')
    process.exit(1)
}
const serviceAccount = JSON.parse(fs.readFileSync(serviceAccountPath, 'utf8'))

// Initialize Admin (for minting tokens)
if (!admin.apps.length) {
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
    })
}

// Initialize Client (for testing rules)
const clientApp = initializeApp(FIREBASE_CONFIG, 'client-app')
const clientAuth = getAuth(clientApp)
const clientDb = getFirestore(clientApp)

async function getClientForUser(email: string) {
    try {
        const user = await admin.auth().getUserByEmail(email)
        const customToken = await admin.auth().createCustomToken(user.uid)
        await signInWithCustomToken(clientAuth, customToken)
        return { uid: user.uid, db: clientDb }
    } catch (e) {
        console.error(`Failed to get client for ${email}:`, e)
        return null
    }
}

async function verifyNotificationPrivacy() {
    console.log('\n🔒 Verifying Notification Privacy...')

    const sarah = await getClientForUser('sarah.chen@example.com')
    const markus = await getClientForUser('markus.weber@example.com')

    if (!sarah || !markus) {
        console.log('  ⚠️ Skipping: Users not found (Run seeding script first)')
        return
    }

    // 1. Create a notification for Sarah (using Admin to bypass rules for setup)
    const notifRef = admin.firestore().collection('notifications').doc()
    await notifRef.set({
        userId: sarah.uid,
        message: 'Secret message for Sarah',
        createdAt: admin.firestore.FieldValue.serverTimestamp()
    })
    console.log('  ✓ Setup: Created notification for Sarah')

    // 2. Sarah tries to read it (Should Succeed)
    try {
        // Re-auth as Sarah
        const sarahToken = await admin.auth().createCustomToken(sarah.uid)
        await signInWithCustomToken(clientAuth, sarahToken)

        const docSnap = await getDoc(doc(clientDb, 'notifications', notifRef.id))
        if (docSnap.exists()) {
            console.log('  ✅ SUCCESS: Sarah can read her own notification')
        } else {
            console.error('  ❌ FAILURE: Sarah cannot read her own notification')
        }
    } catch (e) {
        console.error('  ❌ FAILURE: Error reading as Sarah:', e)
    }

    // 3. Markus tries to read it (Should Fail)
    try {
        // Re-auth as Markus
        const markusToken = await admin.auth().createCustomToken(markus.uid)
        await signInWithCustomToken(clientAuth, markusToken)

        await getDoc(doc(clientDb, 'notifications', notifRef.id))
        console.error('  ❌ FAILURE: Markus was able to read Sarah\'s notification')
    } catch (e: any) {
        if (e.code === 'permission-denied') {
            console.log('  ✅ SUCCESS: Markus blocked from reading Sarah\'s notification')
        } else {
            console.error('  ⚠️ UNEXPECTED ERROR reading as Markus:', e)
        }
    }
}

async function main() {
    console.log('🛡️  Privacy Verification Script')
    console.log('================================')

    try {
        await verifyNotificationPrivacy()
    } catch (e) {
        console.error('Script error:', e)
    }

    // Cleanup
    process.exit(0)
}

main()
